import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    chatsContainer:{
        //backgroundColor:'#E9F3FF'
    },
    containerChat:{
        marginVertical:10,
        paddingHorizontal:20,
        borderBottomColor:'lightgray',
        paddingBottom:20,
        borderBottomWidth:1
    },
    pictureAndUsernameContainer:{
        display:'flex',
        flexDirection:'row',
        marginBottom:10
    },
    name:{
        position:'absolute',
        left:15,
        top:10,
        zIndex:99,
        color:'#fff',
        fontFamily:'Adam-Bold'
    },
    dateContainer:{
        display:'flex',
        justifyContent:'center',
        alignItems:'flex-end',
        flex:1
    },
    date:{
        color:'gray',
        textAlignVertical:'center',
        fontFamily:'Inter-Black-Light'
    },
    pictureContainer:{
        borderRadius:25,
        width:50,
        height:50,
        color:'#fff',
        marginRight:20

    },
    username:{
        fontSize:20,
        textAlignVertical:'center',
        fontFamily:'Inter-Black-Light'
    },
    chatSubject:{
        fontSize:16,
        marginTop:5,
        fontFamily:'Inter-Black-Light'
    },
    chatText:{
        color:'gray',
        marginTop:5,
    }
})